require 'rest-client'
require 'json'

top_artists = [
    "The Beatles",
"The Beach Boys",
"Bob Dylan",
"Marvin Gaye",
"The Rolling Stones",
"The Clash",
"Elvis Presley",
"Miles Davis",
"The Velvet Underground",
"The Jimi Hendrix Experience",
"Nirvana",
"Bruce Springsteen",
"Van Morrison",
"Michael Jackson",
"Chuck Berry",
"Robert Johnson",
"John Lennon / Plastic Ono Band",
"Stevie Wonder",
"James Brown",
"Fleetwood Mac",
"U2",
"The Who",
"Led Zeppelin",
"Joni Mitchell",
"Ramones",
"The Band",
"David Bowie",
"Carole King",
"Eagles",
"Muddy Waters",
"Love",
"Sex Pistols",
"The Doors",
"Pink Floyd",
"Patti Smith",
"Bob Marley & The Wailers",
"John Coltrane",
"Public Enemy",
"The Allman Brothers Band",
"Little Richard",
"Simon & Garfunkel",
"Al Green",
"Ray Charles",
"Creedence Clearwater Revival",
"Captain Beefheart & His Magic Band",
"Sly & The Family Stone",
"Guns N' Roses",
"Phil Spector",
"Radiohead",
"Billy Joel",
"Paul Simon",
"Curtis Mayfield",
"Neil Young",
"Prince and the Revolution",
"AC/DC",
"Otis Redding",
"John Lennon",
"Aretha Franklin",
"Johnny Cash",
"Dusty Springfield",
"Elton John",
"Buddy Holly",
"Prince",
"Hank Williams",
"Elvis Costello",
"The Zombies",
"Frank Sinatra",
"Cream",
"James Taylor",
"Sam Cooke",
"The Mamas and the Papas",
"Derek and the Dominos",
"Kanye West",
"Etta James",
"The Byrds",
"Various Artists",
"Run D.M.C.",
"Moby Grape",
"Janis Joplin",
"The Wailers",
"Iggy and The Stooges",
"Talking Heads",
"Television",
"Black Sabbath",
"The Notorious B.I.G.",
"Pavement",
"The Replacements",
"Dr. Dre",
"The Meters",
"Blondie",
"B.B. King",
"Dr. John, the Night Tripper",
"N.W.A",
"Steely Dan",
"Jefferson Airplane",
"Crosby, Stills, Nash & Young",
"Santana",
"Arcade Fire",
"The B 52's",
"A Tribe Called Quest",
"Howlin' Wolf",
"Pretenders",
"Beastie Boys",
"Joy Division",
"KISS",
"T. Rex",
"Linda Ronstadt",
"Elvis Costello & The Attractions",
"Metallica",
"Rod Stewart",
"Todd Rundgren",
"Carpenters",
"Aerosmith",
"Funkadelic",
"Curtis Mayfield and The Impressions",
"ABBA",
"Willie Nelson",
"Madonna",
"The Stooges",
"Peter Gabriel",
"Buffalo Springfield",
"Quicksilver Messenger Service",
"The Flying Burrito Brothers",
"Green Day",
"Lou Reed",
"John Mayall & The Bluesbreakers",
"R.E.M.",
"Little Walter",
"The Strokes",
"Nine Inch Nails",
"Cat Stevens",
"Pearl Jam",
"Neil Young & Crazy Horse",
"Ike & Tina Turner",
"New York Dolls",
"Bo Diddley",
"The Smiths",
"My Bloody Valentine",
"Professor Longhair",
"Neil Diamond",
"Pixies",
"Eric B. & Rakim",
"Bonnie Raitt",
"Queen",
"The Kinks",
"Patsy Cline",
"Jackie Wilson",
"Eminem",
"Jerry Lee Lewis",
"The Mothers of Invention",
"The Grateful Dead",
"Ornette Coleman",
"Jay Z",
"Kraftwerk",
"Whitney Houston",
"Janet",
"Grateful Dead",
"Crosby, Stills & Nash",
"Tracy Chapman",
"Blood, Sweat & Tears",
"The Jesus and Mary Chain",
"Sleater Kinney",
"Smokey Robinson & The Miracles",
"LaBelle",
"Parliament",
"Janet Jackson",
"Various",
"Mary J. Blige",
"Barry White",
"The Cars",
"X",
"Bob Dylan and the Band",
"MC5",
"Leonard Cohen",
"Weezer",
"Dolly Parton",
"Jeff Buckley",
"Lucinda Williams",
"Beck",
"Red Hot Chili Peppers",
"Jane's Addiction",
"Lauryn Hill",
"Tom Petty and the Heartbreakers",
"The O'Jays",
"Nick Drake",
"Randy Newman",
"The Police",
"Eric Clapton",
"The Cure",
"Liz Phair",
"Sonic Youth",
"Richard & Linda Thompson",
"Graham Parker & The Rumour",
"Soundgarden",
"Jethro Tull",
"Big Brother & the Holding Company",
"Tom Waits",
"Black Flag",
"Moby",
"Depeche Mode",
"Meat Loaf",
"De La Soul",
"The Yardbirds",
"Dire Straits",
"Buzzcocks",
"OutKast",
"The Smashing Pumpkins",
"New Order",
"Rage Against the Machine",
"Mott the Hoople",
"Arctic Monkeys",
"Roxy Music",
"Jackson Browne",
"Bjork",
"John Lee Hooker",
"Oasis",
"TLC",
"Toots & The Maytals",
"The Modern Lovers",
"Wu Tang Clan",
"Don Henley",
"The White Stripes",
"M.I.A.",
"LCD Soundsystem",
"Massive Attack",
"ZZ Top",
"The Temptations",
"Nas",
"Lynyrd Skynyrd",
"Dr. John",
"Big Star",
"PJ Harvey",
"Sinead O'Connor",
"Wire",
"Minutemen",
"The Go Go's",
"Van Halen",
"Paul McCartney & Wings",
"Portishead",
"The Crickets",
"The Ronettes",
"Diana Ross & The Supremes",
"Gram Parsons",
"Cheap Trick",
"Peter Wolf",
"Brian Eno",
"Vampire Weekend",
"George Harrison",
"Lil Wayne",
"The Pogues",
"Suicide",
"DEVO",
"War",
"Steve Miller Band",
"Stan GetzÊ/ÊJoao GilbertoÊfeaturingÊAntonio Carlos Jobim",
"Amy Winehouse",
"John Prine",
"EPMD",
"Alice Cooper",
"Los Lobos",
"My Morning Jacket",
"The Drifters",
"Hole",
"Public Image Ltd.",
"Echo and The Bunnymen",
"Def Leppard",
"The Magnetic Fields",
"Coldplay",
"The Paul Butterfield Blues Band",
"Fugees",
"L.L. Cool J",
"George Michael",
"Manu Chao",
"Merle Haggard",
"Loretta Lynn",
"Raekwon",
"D'Angelo",
"Steve Earle",
"Gang of Four",
"Earth, Wind & Fire",
"Cyndi Lauper",
"Husker Du",
"Albert King",
"Eurythmics",
"Wilco",
"MGMT",
"Boz Scaggs",
"The Stone Roses"
]


